/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _DemoInputRoute } from '../pages/demo/input';
import { Route as _DemoMainRoute } from '../pages/demo/main';
import { Route as _DemoModalRoute } from '../pages/demo/modal';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/demo/input': (typeof _DemoInputRoute)['_inputType'];
    '/demo/main': (typeof _DemoMainRoute)['_inputType'];
    '/demo/modal': (typeof _DemoModalRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/demo/input': (typeof _DemoInputRoute)['_outputType'];
    '/demo/main': (typeof _DemoMainRoute)['_outputType'];
    '/demo/modal': (typeof _DemoModalRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
